@extends('skeleton')

@section("content")
    @include('sections.titleSection')
    @include('sections.case')
    @include('sections.industries')
    @include('sections.wecreate')
    @include('sections.sec-a-3')
    @include('sections.partners')
    @include('sections.our-platform')
    @include('sections.benefits')
    @include('sections.feedback')
    @include('sections.question')
    @include('sections.lets-us')
@endsection
